#!/bin/bash
set -e

setup() {
  echo "=== Running system setup ==="
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "sujan"
  echo "=== Setup completed successfully ==="
}

case "$1" in
  setup) setup ;;
  *)
    echo "Usage: $0 {setup}"
    exit 1
    ;;
esac
